// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPe4MdFEGCDp9UyxTgAip4Vgy2PI66SFc',
    appId: '1:425174209550:web:f37303f822164023e9185f',
    messagingSenderId: '425174209550',
    projectId: 'hotellio-app',
    authDomain: 'hotellio-app.firebaseapp.com',
    storageBucket: 'hotellio-app.appspot.com',
    measurementId: 'G-6KLD2R5GZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEdjPMC1EBmprc5p-QUYxsPUSuviomGM',
    appId: '1:425174209550:android:0922e247917f89cce9185f',
    messagingSenderId: '425174209550',
    projectId: 'hotellio-app',
    storageBucket: 'hotellio-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2g4PhkHUL9ASCQfVaRP9pBY86_D9JDUM',
    appId: '1:425174209550:ios:1944f92ba42a9363e9185f',
    messagingSenderId: '425174209550',
    projectId: 'hotellio-app',
    storageBucket: 'hotellio-app.appspot.com',
    iosClientId: '425174209550-6424n5rhv6c8ll68mmk0c7dr6nuqh9po.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2g4PhkHUL9ASCQfVaRP9pBY86_D9JDUM',
    appId: '1:425174209550:ios:1944f92ba42a9363e9185f',
    messagingSenderId: '425174209550',
    projectId: 'hotellio-app',
    storageBucket: 'hotellio-app.appspot.com',
    iosClientId: '425174209550-6424n5rhv6c8ll68mmk0c7dr6nuqh9po.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelsApp',
  );
}
